<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="DESKTOP-QKI5LTU" name="org.tng.Testng5" tests="13" failures="1" timestamp="2020-07-02T15:29:47 IST" time="0.044" errors="0">
  <testcase name="launch" time="0.001" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.003" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="payment" time="0.002" classname="org.tng.Testng5"/>
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at org.tng.Testng5.launch(Testng5.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.002" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="launch" time="0.007" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase name="cancel" time="0.014" classname="org.tng.Testng5"/>
  <system-out/>
  <testcase name="launch" time="0.003" classname="org.tng.Testng5">
    <skipped/>
  </testcase> <!-- launch -->
  <system-out/>
</testsuite> <!-- org.tng.Testng5 -->
